In [2]:
import numpy as np
from numpy.ma.core import reshape

ary = np.arange(12).reshape(3, 4)

In [3]:
ary.ndim, ary.shape, ary.size, len(ary)

(2, (3, 4), 12, 3)

In [4]:

ary = np.arange(24).reshape(2, 3, 4)
print(ary)
print(ary[1])
print(ary[1, 2])
print(ary[1, 2, 3])
print(ary[1][2])
print(ary[1][2][3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[20 21 22 23]
23
[20 21 22 23]
23


In [5]:
for i in range(ary.shape[0]):
    for j in range(ary.shape[1]):
        for k in range(ary.shape[2]):
            print(ary[i, j, k])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


### numpy的数据类型 和 缩写
https://cloud.tencent.com/developer/article/1755021




In [6]:
var = np.dtype(np.float64)
print(var, type(var))

float64 <class 'numpy.dtypes.Float64DType'>


In [7]:
### 自定义复合类型--类

data = [
    ('zhangsan', [98, 80, 85], 15),
    ('lisi', [92, 81, 83], 16),
    ('wangwu', [95, 85, 95], 14),
]

# scores = np.array(data)
## U在基础数据类型时,会自动推断长度
data2 = np.array(['aa', 'bbb', 'cccc', 'ddddd'], dtype='U')
print(data2, data2.dtype)

## 这里不能直接写U,不会自动推断结构化数据的长度,解决办法,要么用object,要么用一个大长度(不推荐,浪费空间)
scores = np.array(data, dtype='U, 3i4, i4')
print(scores, scores.dtype)
scores = np.array(data, dtype='O, 3i4, i4')
print(scores, scores.dtype)
### 结构化数据怎么访问 f1, f2代表field1 field2
print('read:', scores[0]['f1'][0])
print('--'*30)
score2 = np.array(data, dtype=[('name', 'str', 2), ('scores', 'int32', 3), ('age', 'int32', 1)])
## 这个时候就没有f0,f1了,已经有明确的字段名字了
print('read:', score2[0]['scores'][0])
print(score2, score2.dtype)
print('--'*30)
score3 = np.array(data, dtype={'names':['name', 'scores', 'age'], 'formats':[
    'U10', '3int32', 'int32'
]})
print('read:', score3[0]['scores'][0])
print(score3, score3.dtype, scores.itemsize)
print('--'*30)

### 不推荐,要控制字节数, 知道就好了
# score4 = np.array(data, dtype={'name': ('U10', 0), 'scores':('3int32', 16), 'age':('int32', 28)})
# print('read:', score4[0]['scores'][0])

## 第一种设置dtype的方式
# scores = np.array(data, dtype='U3, 3i4, i4')
# scores = np.array(data, dtype='<U10, 3i4, i4')
# scores = np.array(data, dtype='O, 3i4, i4')

## 第二种设置dtype的方式
# score2 = np.array(data, dtype=[('name', 'str', 2), ('scores', 'int32', 3), ('age', 'int32', 1)])

## 第三种设置dtype的方式
# score3 = np.array(data, dtype={'names':['name', 'scores', 'age'], 'formats':[
#     'U10', '3int32', 'int32'
# ]})


['aa' 'bbb' 'cccc' 'ddddd'] <U5
[('', [98, 80, 85], 15) ('', [92, 81, 83], 16) ('', [95, 85, 95], 14)] [('f0', '<U'), ('f1', '<i4', (3,)), ('f2', '<i4')]
[('zhangsan', [98, 80, 85], 15) ('lisi', [92, 81, 83], 16)
 ('wangwu', [95, 85, 95], 14)] [('f0', 'O'), ('f1', '<i4', (3,)), ('f2', '<i4')]
read: 98
------------------------------------------------------------
read: 98
[('zh', [98, 80, 85], [15]) ('li', [92, 81, 83], [16])
 ('wa', [95, 85, 95], [14])] [('name', '<U2'), ('scores', '<i4', (3,)), ('age', '<i4', (1,))]
------------------------------------------------------------
read: 98
[('zhangsan', [98, 80, 85], 15) ('lisi', [92, 81, 83], 16)
 ('wangwu', [95, 85, 95], 14)] [('name', '<U10'), ('scores', '<i4', (3,)), ('age', '<i4')] 24
------------------------------------------------------------


In [8]:
## 测试日期类型的数据 datetime64
from datetime import datetime

data = ['2025', '2025-01-12', '2025-12', '2025-12-20 12:23:23']
date_arr  = np.array(data)
print(date_arr, date_arr.dtype)
date_arr = np.array(data, dtype='datetime64[D]')
print(date_arr, date_arr.dtype)
date_arr = np.array(data, dtype='M8[s]')
print(date_arr, date_arr.dtype)
### 两个是完全不同的日期类型
print(date_arr[0], type(date_arr[0]), datetime.now(), type(datetime.now()))

## 日期差
dis = date_arr[1] - date_arr[2]
print(dis, type(dis))

date_arr = date_arr.astype('M8[D]')
dis = date_arr[1] - date_arr[2]
print(dis, type(dis))

['2025' '2025-01-12' '2025-12' '2025-12-20 12:23:23'] <U19
['2025-01-01' '2025-01-12' '2025-12-01' '2025-12-20'] datetime64[D]
['2025-01-01T00:00:00' '2025-01-12T00:00:00' '2025-12-01T00:00:00'
 '2025-12-20T12:23:23'] datetime64[s]
2025-01-01T00:00:00 <class 'numpy.datetime64'> 2025-03-31 22:27:20.814448 <class 'datetime.datetime'>
-27907200 seconds <class 'numpy.timedelta64'>
-323 days <class 'numpy.timedelta64'>


In [9]:

### 视图维度变更
a = np.arange(12)
print(a, a.shape)
b = a.reshape(3, 4)
print(b, b.shape)
c = a.ravel()
print(c, c.shape)
d = a.repeat(3, axis=0)
print(d, d.shape)
e = a.reshape(3, 4).repeat(3, axis=0)
print(e, e.shape)
f = a.reshape(3, 4).repeat(3, axis=1)
print(f, f.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 10 10 11 11 11] (36,)
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]
 [ 8  9 10 11]] (9, 4)
[[ 0  0  0  1  1  1  2  2  2  3  3  3]
 [ 4  4  4  5  5  5  6  6  6  7  7  7]
 [ 8  8  8  9  9  9 10 10 10 11 11 11]] (3, 12)


In [10]:
## 一维变更
aa = np.arange(12)
bb = aa.ravel() ## 浅拷贝
bb[0] = 100
print(bb, aa)
cc = aa.flatten() ## 深拷贝
cc[1] = 10000
print(cc, aa)

## 就地变维 -- 直接更改原对象
aa.shape = (3, 4)
print(aa.shape, aa)
print('----------')
aa.resize((4, 3))
print(aa, aa.shape)
print('----------')
aa.resize((6, 2)) ## 不能写-1, 这个和reshape有本质区别
print(aa, aa.shape)


[100   1   2   3   4   5   6   7   8   9  10  11] [100   1   2   3   4   5   6   7   8   9  10  11]
[  100 10000     2     3     4     5     6     7     8     9    10    11] [100   1   2   3   4   5   6   7   8   9  10  11]
(3, 4) [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
----------
[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]] (4, 3)
----------
[[100   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]
 [ 10  11]] (6, 2)


In [11]:
a = np.arange(12)
print(a)
print(a[:3])
print(a[3:6])
print(a[6:])
print(a[:-1])
print(a[:-4:-1])
print(a[-4:-7:-1])
print(a[::])
print(a[:])
print(a[::2])
print(a[1::3])
print(a[4::4])


b = a[2:6] ##浅拷贝 -- 这个是数组
print(b)
b[3] = 99999
print(b, a)

xx = [i for i in range(12)]
yy = xx[2:6] ##深拷贝 -- 这个是列表
yy[3] = 888888
print(xx, yy)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2]
[3 4 5]
[ 6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10]
[11 10  9]
[8 7 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10]
[ 1  4  7 10]
[4 8]
[2 3 4 5]
[    2     3     4 99999] [    0     1     2     3     4 99999     6     7     8     9    10    11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] [2, 3, 4, 888888]


In [12]:
## 多位数组切片
a = np.arange(1, 28).reshape(3, 3, 3)
print(a[1,1,1])
print(a[1,:,:])
print(a[1,:, 1])

14
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[11 14 17]


In [13]:
### 掩码运算
c = np.array([[1, 100], [200, 2]])
mask = c > 50
print(mask)
c[mask] = 999999 ## 掩码的为true的位置进行赋值
print(c)
print(c[mask]) ## 经过掩码后,变成一维数组

print('------------------------------')
a = np.arange(0, 100).reshape(10, 10)
print(a[(a % 3 == 0) & (a % 5 == 0)])
print(a[(a % 3 == 0) | (a % 5 == 0)])


cc = np.array(['A', 'B', 'C', 'D'])
mask = [3, 0 , 2, 0 , 0 , 1, 3, 0 , 1] ##掩码赋值
print(cc[mask])

[[False  True]
 [ True False]]
[[     1 999999]
 [999999      2]]
[999999 999999]
------------------------------
[ 0 15 30 45 60 75 90]
[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
['D' 'A' 'C' 'A' 'A' 'B' 'D' 'A' 'B']


In [14]:

## 多维度数组组合拆分

a = np.arange(0, 6).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

c = np.vstack((a, b))
print(c)

d = np.hstack((a, b))
print(d)

e, f = np.vsplit(c, 2)
print(e, f)

h, i = np.hsplit(d, 2)
print(h, i)

aa = np.dstack((a, b))
print(aa)


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
[[0 1 2]
 [3 4 5]] [[ 7  8  9]
 [10 11 12]]
[[0 1 2]
 [3 4 5]] [[ 7  8  9]
 [10 11 12]]
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [15]:
## pad操作

x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([4, 5])
## pad_width的意思:before, after, 前面插入几个,后面插入几个
z = np.pad(y, pad_width=(1, 2), mode='constant', constant_values=0)
print(z)
## pad_width是数组时, 第一个代表一维方向,第二个代表二维方向,也是before和after的意思
m = np.pad(x, pad_width=[(1, 2),(3, 4)], mode='constant', constant_values=0)
print(m)

[0 4 5 0 0]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 0 0 0 0]
 [0 0 0 3 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [16]:
## 组合和拆分的终极大招
m = np.arange(1, 10).reshape(3, 3)
n = np.arange(11, 20).reshape(3, 3)
x = np.concatenate([m, n], axis=0)
print(x)
y = np.concatenate([m, n], axis=1)
print(y)
x0, x1 = np.split(x, 2, axis=0)
print(x0, x1)
y0, y1 = np.split(y, 2, axis=1)
print(y0, y1)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [17]:
## ndarray其他属性

a = np.arange(10).reshape(2, 5)
## int64-8字节 总共占用8*10=80字节
print(a.itemsize, a.nbytes, a.T)

## a.flat扁平迭代器
for x in a.flat:
    print(x)

8 80 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
0
1
2
3
4
5
6
7
8
9


NumPy 提供了丰富的基础数据类型（`dtype`），这些类型用于定义数组中元素的性质。它们主要基于 C 语言的数据类型，但 NumPy 对其进行了扩展和封装，使其更灵活且与 Python 无缝集成。以下是 NumPy 的基础数据类型的分类和详细说明：

---

### 1. **整数类型（Integer Types）**
NumPy 支持多种位宽的有符号和无符号整数类型：
- **有符号整数**：
  - `int8`：8 位整数（-128 到 127）
  - `int16`：16 位整数（-32,768 到 32,767）
  - `int32`：32 位整数（-2,147,483,648 到 2,147,483,647）
  - `int64`：64 位整数（-9,223,372,036,854,775,808 到 9,223,372,036,854,775,807）
- **无符号整数**：
  - `uint8`：8 位无符号整数（0 到 255）
  - `uint16`：16 位无符号整数（0 到 65,535）
  - `uint32`：32 位无符号整数（0 到 4,294,967,295）
  - `uint64`：64 位无符号整数（0 到 18,446,744,073,709,551,615）
- **默认整数**：
  - `int_`：平台相关的默认整数类型（通常是 `int64` 或 `int32`，取决于系统）。

---

### 2. **浮点数类型（Floating-Point Types）**
用于表示小数，支持不同的精度：
- `float16`：16 位半精度浮点数（较小的范围和精度）。
- `float32`：32 位单精度浮点数（约 7 位十进制精度）。
- `float64`：64 位双精度浮点数（约 15-17 位十进制精度）。
- `float128`：128 位扩展精度浮点数（依赖于平台支持，可能不可用）。
- **默认浮点数**：
  - `float_`：默认是 `float64`。

---

### 3. **复数类型（Complex Types）**
用于表示复数，包含实部和虚部：
- `complex64`：由两个 `float32` 组成（实部和虚部各 32 位）。
- `complex128`：由两个 `float64` 组成（实部和虚部各 64 位）。
- `complex256`：由两个 `float128` 组成（依赖平台支持）。
- **默认复数**：
  - `complex_`：默认是 `complex128`。

---

### 4. **布尔类型（Boolean Type）**
- `bool`：布尔值（`True` 或 `False`），占用 8 位（1 字节）。
- **注意**：与 Python 的 `bool` 类型兼容，但固定为 1 字节存储。

---

### 5. **字符串类型（String Types）**
用于存储固定长度的字符串：
- `string_` 或 `S`：固定长度的字节字符串（如 `S10` 表示长度为 10 的字节字符串）。
- **示例**：`np.array(['abc', 'def'], dtype='S3')` 会创建长度为 3 的字节字符串数组。
- **注意**：默认编码是字节形式（`bytes`），而不是 Unicode。

---

### 6. **Unicode 字符串类型（Unicode String Types）**
用于存储固定长度的 Unicode 字符串：
- `unicode_` 或 `U`：固定长度的 Unicode 字符串（如 `U10` 表示长度为 10 的 Unicode 字符串）。
- **示例**：`np.array(['你好', '世界'], dtype='U2')`。

---

### 7. **时间类型（Datetime and Timedelta Types）**
用于处理日期、时间和时间间隔：
- `datetime64`：日期时间类型，支持多种单位（如 `datetime64[ns]` 表示纳秒精度）。
- `timedelta64`：时间差类型，同样支持多种单位（如 `timedelta64[ms]` 表示毫秒）。
- **示例**：
  ```python
  np.array(['2025-03-20', '2025-03-21'], dtype='datetime64[D]')  # 按天存储
  ```

---

### 8. **对象类型（Object Type）**
- `object` 或 `O`：允许存储任意 Python 对象（灵活但性能较低）。
- **示例**：`np.array([1, "string", [1, 2, 3]], dtype=object)`。

---

### 9. **字节顺序（Byte Order）**
NumPy 数据类型可以指定字节顺序（大端或小端）：
- `<`：小端（little-endian，如 `<i4` 表示小端 32 位整数）。
- `>`：大端（big-endian，如 `>f8` 表示大端 64 位浮点数）。
- 默认通常是系统原生字节顺序。

---

### 示例代码
```python
import numpy as np

# 不同数据类型的数组
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.5, 2.5], dtype=np.float64)
complex_arr = np.array([1+2j, 3+4j], dtype=np.complex128)
bool_arr = np.array([True, False], dtype=np.bool_)
string_arr = np.array(['abc', 'def'], dtype='S3')
unicode_arr = np.array(['你好', '世界'], dtype='U2')
datetime_arr = np.array(['2025-03-20'], dtype='datetime64[D]')

# 打印类型
print(int_arr.dtype)        # int32
print(float_arr.dtype)      # float64
print(complex_arr.dtype)    # complex128
print(bool_arr.dtype)       # bool
print(string_arr.dtype)     # |S3
print(unicode_arr.dtype)    # <U2
print(datetime_arr.dtype)   # datetime64[D]
```

---

### 如何指定数据类型
- 在创建数组时通过 `dtype` 参数指定：`np.array([1, 2, 3], dtype=np.float32)`。
- 使用简写：`np.array([1, 2, 3], dtype='f4')`（`f4` 表示 `float32`）。
- 转换类型：`arr.astype(np.int16)`。

---

### 总结
NumPy 的基础数据类型非常丰富，涵盖整数、浮点数、复数、布尔值、字符串、时间等，适用于各种科学计算场景。这些类型的选择会影响内存使用和计算性能，因此在实际应用中需要根据需求权衡精度和效率。

NumPy 的基础数据类型可以用简写（简洁的字符串表示）来指定，这些简写通常用于 `dtype` 参数。以下是 NumPy 基础数据类型的简写及其对应的类型说明：

---

### 1. **整数类型（Integer Types）**
- **有符号整数**：
  - `i1`：`int8`（8 位）
  - `i2`：`int16`（16 位）
  - `i4`：`int32`（32 位）
  - `i8`：`int64`（64 位）
  - `i`：默认整数类型（`int_`，通常是 `i8` 或 `i4`，取决于平台）
- **无符号整数**：
  - `u1`：`uint8`（8 位）
  - `u2`：`uint16`（16 位）
  - `u4`：`uint32`（32 位）
  - `u8`：`uint64`（64 位）
  - `u`：默认无符号整数类型（`uint_`，通常是 `u8` 或 `u4`）

---

### 2. **浮点数类型（Floating-Point Types）**
- `f2`：`float16`（16 位半精度）
- `f4`：`float32`（32 位单精度）
- `f8`：`float64`（64 位双精度）
- `f16` 或 `f`：`float128`（128 位，平台相关，若不支持则可能是 `float64`）
- 默认：`f` 通常表示 `float64`

---

### 3. **复数类型（Complex Types）**
- `c8`：`complex64`（由两个 `float32` 组成）
- `c16`：`complex128`（由两个 `float64` 组成）
- `c32`：`complex256`（由两个 `float128` 组成，平台相关）
- 默认：`c` 通常表示 `complex128`

---

### 4. **布尔类型（Boolean Type）**
- `b`：`bool`（8 位布尔值）

---

### 5. **字符串类型（String Types）**
- `S#`：字节字符串，`#` 表示长度（如 `S10` 表示长度为 10 的字节字符串）
- 默认：`S`（无长度指定时，通常由数据推断）

---

### 6. **Unicode 字符串类型（Unicode String Types）**
- `U#`：Unicode 字符串，`#` 表示长度（如 `U10` 表示长度为 10 的 Unicode 字符串）
- 默认：`U`（无长度指定时，通常由数据推断）

---

### 7. **时间类型（Datetime and Timedelta Types）**
- `M8[unit]`：`datetime64`，`unit` 指定时间单位（如 `M8[D]` 表示按天，`M8[ns]` 表示按纳秒）
- `m8[unit]`：`timedelta64`，`unit` 指定时间单位（如 `m8[s]` 表示按秒）
- 常用单位简写：
  - `Y`：年
  - `M`：月
  - `D`：日
  - `h`：小时
  - `m`：分钟
  - `s`：秒
  - `ms`：毫秒
  - `us`：微秒
  - `ns`：纳秒

---

### 8. **对象类型（Object Type）**
- `O`：`object`（任意 Python 对象）

---

### 9. **字节顺序（Byte Order）**
- `<`：小端（little-endian，如 `<i4` 表示小端 32 位整数）
- `>`：大端（big-endian，如 `>f8` 表示大端 64 位浮点数）
- `|`：无关字节顺序（通常用于 `bool` 或 `S`/`U`，如 `|S10`）
- 默认：不写字节顺序时，使用系统原生顺序

---

### 示例代码
```python
import numpy as np

# 使用简写创建数组
int_arr = np.array([1, 2, 3], dtype='i4')         # int32
uint_arr = np.array([1, 2, 3], dtype='u2')        # uint16
float_arr = np.array([1.5, 2.5], dtype='f4')      # float32
complex_arr = np.array([1+2j], dtype='c16')       # complex128
bool_arr = np.array([True, False], dtype='b')     # bool
string_arr = np.array(['abc', 'def'], dtype='S3') # 长度为 3 的字节字符串
unicode_arr = np.array(['你好'], dtype='U2')      # 长度为 2 的 Unicode 字符串
datetime_arr = np.array(['2025-03-20'], dtype='M8[D]')  # 按天存储的 datetime64

# 打印类型
print(int_arr.dtype)        # int32
print(uint_arr.dtype)       # uint16
print(float_arr.dtype)      # float32
print(complex_arr.dtype)    # complex128
print(bool_arr.dtype)       # bool
print(string_arr.dtype)     # |S3
print(unicode_arr.dtype)    # <U2
print(datetime_arr.dtype)   # datetime64[D]
```

---

### 注意事项
1. **长度指定**：对于 `S` 和 `U`，长度是可选的。如果不指定长度，NumPy 会根据输入数据的最大长度自动推断。
2. **默认类型**：不指定 `dtype` 时，NumPy 会根据输入数据推断类型（如整数默认 `int_`，浮点数默认 `float_`）。
3. **字节顺序**：通常不需要显式指定，除非处理跨平台数据或特定需求。

这些简写是 NumPy 的强大特性之一，简洁且直观，方便在代码中快速指定数据类型.

`timedelta64` 是 NumPy 中用于表示**时间差**（时间间隔）的数据类型，而不是表示某个具体的时间点。它属于 NumPy 的时间相关数据类型家族，与 `datetime64`（表示具体日期和时间）一起使用，广泛应用于时间序列计算。

以下是对 `timedelta64` 时间格式的详细说明：

---

### 1. **基本定义**
- `timedelta64` 表示两个时间点之间的差值，可以是正值（未来时间减去过去时间）或负值（过去时间减去未来时间）。
- 它的值由两部分组成：
  - **数值**：表示时间差的大小。
  - **单位**：指定时间差的计量单位（如秒、分钟、天等）。

---

### 2. **时间单位**
`timedelta64` 的时间格式通过单位来定义，单位在 `dtype` 中以 `[unit]` 的形式指定。支持的单位包括：
- `Y`：年
- `M`：月
- `W`：周
- `D`：天
- `h`：小时
- `m`：分钟
- `s`：秒
- `ms`：毫秒
- `us`：微秒（μs）
- `ns`：纳秒
- `ps`：皮秒
- `fs`：飞秒
- `as`：阿秒

例如：
- `timedelta64[D]` 表示时间差以天为单位。
- `timedelta64[ms]` 表示时间差以毫秒为单位。

---

### 3. **创建方式**
可以通过以下方式创建 `timedelta64` 对象：
- **直接指定**：
  ```python
  import numpy as np
  td = np.timedelta64(1, 'D')  # 1 天
  print(td)  # 1 days
  ```
- **时间差计算**（从 `datetime64` 相减）：
  ```python
  t1 = np.datetime64('2025-03-20')
  t2 = np.datetime64('2025-03-22')
  td = t2 - t1  # 计算时间差
  print(td)  # 2 days
  print(td.dtype)  # timedelta64[ns]（默认以纳秒为单位）
  ```

---

### 4. **默认格式和精度**
- 当两个 `datetime64` 对象相减时，生成的 `timedelta64` 默认精度取决于输入的 `datetime64` 精度，通常是**纳秒（`ns`）**。
- 你可以通过显式转换来调整单位：
  ```python
  td = np.timedelta64(3600, 's')  # 3600 秒
  td_in_hours = td.astype('timedelta64[h]')  # 转换为小时
  print(td_in_hours)  # 1 hours
  ```

---

### 5. **存储和表示**
- **存储**：`timedelta64` 在内存中存储为 64 位整数，单位决定了这个整数的含义。例如，`timedelta64[D]` 的值 2 表示 2 天。
- **表示**：在输出时，NumPy 会以人类可读的形式显示（如 `2 days`、`3600 seconds`），但底层仍是一个数值和单位的组合。

---

### 6. **与 Python 的 `timedelta` 对比**
- Python 标准库中的 `datetime.timedelta` 只支持天、秒和微秒的组合，精度和单位范围较窄。
- NumPy 的 `timedelta64` 支持更广泛的单位（从阿秒到年），并且与 `datetime64` 无缝集成，适合高性能数组计算。

---

### 示例代码
```python
import numpy as np

# 创建不同单位的 timedelta64
td1 = np.timedelta64(2, 'D')    # 2 天
td2 = np.timedelta64(3600, 's') # 3600 秒
td3 = np.timedelta64(500, 'ms') # 500 毫秒

print(td1)  # 2 days
print(td2)  # 3600 seconds
print(td3)  # 500 milliseconds

# 时间差计算
t1 = np.datetime64('2025-03-20 10:00')
t2 = np.datetime64('2025-03-20 12:30')
diff = t2 - t1
print(diff)  # 9000000000000 nanoseconds (2.5小时转换为纳秒)

# 转换为其他单位
diff_in_minutes = diff.astype('timedelta64[m]')
print(diff_in_minutes)  # 150 minutes
```

---

### 7. **实际应用**
- **时间序列分析**：计算时间间隔，如每日销售额的差值。
- **数据对齐**：调整时间戳之间的偏移。
- **批量计算**：对数组中的时间差进行矢量化操作。

---

### 总结
`timedelta64` 不是传统意义上的“时间格式”（如 `YYYY-MM-DD`），而是一种**时间差的表示方式**，由数值和单位共同定义。它的灵活性在于支持多种时间单位（从阿秒到年），并且可以与 `datetime64` 配合使用。具体的“格式”取决于你指定的单位（如 `timedelta64[D]` 表示以天为单位的时间差）。

以下是用表格形式整理的 NumPy 基础数据类型及其简写、字节大小、范围等信息的详细描述。表格按类型分类，便于直观理解。

---

### 表格：NumPy 基础数据类型、简写及其他信息

#### 1. 整数类型（Integer Types）
| **类型**     | **简写** | **字节大小** | **范围**                                      | **说明**                  |
|--------------|----------|--------------|-----------------------------------------------|---------------------------|
| `int8`       | `i1`     | 1 (8 位)    | -128 到 127                                   | 8 位有符号整数            |
| `int16`      | `i2`     | 2 (16 位)   | -32,768 到 32,767                            | 16 位有符号整数           |
| `int32`      | `i4`     | 4 (32 位)   | -2,147,483,648 到 2,147,483,647              | 32 位有符号整数           |
| `int64`      | `i8`     | 8 (64 位)   | -9,223,372,036,854,775,808 到 9,223,372,036,854,775,807 | 64 位有符号整数           |
| `uint8`      | `u1`     | 1 (8 位)    | 0 到 255                                      | 8 位无符号整数            |
| `uint16`     | `u2`     | 2 (16 位)   | 0 到 65,535                                   | 16 位无符号整数           |
| `uint32`     | `u4`     | 4 (32 位)   | 0 到 4,294,967,295                            | 32 位无符号整数           |
| `uint64`     | `u8`     | 8 (64 位)   | 0 到 18,446,744,073,709,551,615               | 64 位无符号整数           |
| `int_`       | `i`      | 平台相关    | 通常等同于 `int64` 或 `int32`                 | 默认有符号整数            |
| `uint_`      | `u`      | 平台相关    | 通常等同于 `uint64` 或 `uint32`               | 默认无符号整数            |

#### 2. 浮点数类型（Floating-Point Types）
| **类型**     | **简写** | **字节大小** | **范围（近似）**                              | **说明**                  |
|--------------|----------|--------------|-----------------------------------------------|---------------------------|
| `float16`    | `f2`     | 2 (16 位)   | ±6.10e-5 到 ±6.55e4 (半精度)                 | 16 位半精度浮点数         |
| `float32`    | `f4`     | 4 (32 位)   | ±1.18e-38 到 ±3.4e38 (约 7 位十进制精度)     | 32 位单精度浮点数         |
| `float64`    | `f8`     | 8 (64 位)   | ±2.23e-308 到 ±1.80e308 (约 15-17 位精度)    | 64 位双精度浮点数         |
| `float128`   | `f16`    | 16 (128 位) | 依赖平台，可能不可用                          | 128 位扩展精度浮点数      |
| `float_`     | `f`      | 8 (64 位)   | 等同于 `float64`                              | 默认浮点数类型            |

#### 3. 复数类型（Complex Types）
| **类型**     | **简写** | **字节大小** | **组成**                | **说明**                  |
|--------------|----------|--------------|-------------------------|---------------------------|
| `complex64`  | `c8`     | 8 (64 位)   | 2 个 `float32` (实部+虚部) | 64 位复数                |
| `complex128` | `c16`    | 16 (128 位) | 2 个 `float64` (实部+虚部) | 128 位复数               |
| `complex256` | `c32`    | 32 (256 位) | 2 个 `float128` (实部+虚部)| 256 位复数（平台相关）    |
| `complex_`   | `c`      | 16 (128 位) | 等同于 `complex128`       | 默认复数类型              |

#### 4. 布尔类型（Boolean Type）
| **类型**     | **简写** | **字节大小** | **范围**                | **说明**                  |
|--------------|----------|--------------|-------------------------|---------------------------|
| `bool`       | `b`      | 1 (8 位)    | `True` 或 `False`       | 8 位布尔值                |

#### 5. 字符串类型（String Types）
| **类型**     | **简写** | **字节大小** | **范围**                | **说明**                  |
|--------------|----------|--------------|-------------------------|---------------------------|
| `string_`    | `S#`     | 可变        | 固定长度字节字符串      | `#` 表示长度，如 `S10`    |

#### 6. Unicode 字符串类型（Unicode String Types）
| **类型**     | **简写** | **字节大小** | **范围**                | **说明**                  |
|--------------|----------|--------------|-------------------------|---------------------------|
| `unicode_`   | `U#`     | 可变        | 固定长度 Unicode 字符串 | `#` 表示长度，如 `U10`    |

#### 7. 时间类型（Datetime and Timedelta Types）
| **类型**     | **简写** | **字节大小** | **单位支持**            | **说明**                  |
|--------------|----------|--------------|-------------------------|---------------------------|
| `datetime64` | `M8[#]`  | 8 (64 位)   | `Y, M, W, D, h, m, s, ms, us, ns, ps, fs, as` | 日期时间，`#` 指定单位，如 `M8[D]` |
| `timedelta64`| `m8[#]`  | 8 (64 位)   | 同上                    | 时间差，`#` 指定单位，如 `m8[s]`   |

#### 8. 对象类型（Object Type）
| **类型**     | **简写** | **字节大小** | **范围**                | **说明**                  |
|--------------|----------|--------------|-------------------------|---------------------------|
| `object`     | `O`      | 平台相关    | 任意 Python 对象        | 用于存储复杂对象，性能较低 |

#### 9. 字节顺序修饰符
| **修饰符**   | **说明**                  | **示例**         |
|--------------|---------------------------|------------------|
| `<`          | 小端（little-endian）     | `<i4` (小端 int32) |
| `>`          | 大端（big-endian）        | `>f8` (大端 float64) |
| `|`          | 无关字节顺序             | `|S10` (字符串)   |

---

### 示例代码
```python
import numpy as np

# 创建不同类型的数组并查看 dtype
types = [
    ('int32', 'i4'), ('uint16', 'u2'), ('float64', 'f8'),
    ('complex128', 'c16'), ('bool', 'b'), ('string', 'S5'),
    ('unicode', 'U5'), ('datetime64[D]', 'M8[D]'), ('timedelta64[s]', 'm8[s]')
]

for name, shorthand in types:
    arr = np.array([], dtype=shorthand)
    print(f"{name}: {arr.dtype}")
```

**输出**：
```
int32: int32
uint16: uint16
float64: float64
complex128: complex128
bool: bool
string: |S5
unicode: <U5
datetime64[D]: datetime64[D]
timedelta64[s]: timedelta64[s]
```

---

### 补充说明
1. **字节大小**：表示单个元素占用的内存空间，影响数组的内存使用。
2. **范围**：对于数值类型，范围由位数和符号决定；字符串和时间类型则由长度或单位定义。
3. **默认类型**：未指定 `dtype` 时，NumPy 根据输入推断（如 `int_`、`float_`）。
4. **时间单位**：`datetime64` 和 `timedelta64` 的单位可以是年 (`Y`) 到阿秒 (`as`)，非常灵活。

这个表格涵盖了 NumPy 基础数据类型的核心信息。如果你需要更详细的某部分说明或具体应用示例，请告诉我！